
version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:6831:6831/udp"
      - "16686:16686"
    networks:
      - opentracing
    
networks:
    opentracing:
        # use the bridge driver, but enable IPv6
        driver: bridge    
